package corbaConversion;


/**
* corbaConversion/IConversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* jeudi 23 novembre 2023 09 h 04 WAT
*/

public interface IConversionRemoteOperations 
{
  double conversionMontant (float mt);
} // interface IConversionRemoteOperations
