package corbaConversion;


/**
* corbaConversion/IConversionRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* jeudi 30 novembre 2023 08 h 41 WAT
*/

public interface IConversionRemote extends IConversionRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IConversionRemote
